# Generated by Django 4.1.5 on 2023-01-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
