# Generated by Django 4.1.5 on 2023-01-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0002_alter_product_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='goldbeans.jpeg', upload_to=''),
        ),
    ]
