# Generated by Django 4.1.5 on 2023-01-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
