# Generated by Django 4.1.5 on 2023-01-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0005_alter_productsinorder_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_confirmed',
        ),
    ]
