# Generated by Django 4.1.5 on 2023-01-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0006_remove_order_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.AlterField(
            model_name='productsinorder',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
