# Generated by Django 4.1.5 on 2023-01-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0012_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.ManyToManyField(to='beansapp.tag'),
        ),
    ]
