# Generated by Django 4.1.5 on 2023-02-16 17:21

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0017_alter_addressee_address_alter_addressee_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressee',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
