# Generated by Django 4.1.5 on 2023-02-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0019_addressee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressee',
            name='username',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='addressee',
            name='address',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='addressee',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
