# Generated by Django 4.1.5 on 2023-02-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0021_alter_addressee_options_alter_addressee_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressee',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
