# Generated by Django 4.1.5 on 2023-02-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0022_alter_addressee_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
