# Generated by Django 4.1.3 on 2023-02-23 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0025_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beansapp.guest'),
        ),
    ]
