# Generated by Django 4.1.3 on 2023-02-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0026_order_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressee',
            name='date_of_birth',
        ),
    ]
