# Generated by Django 4.1.5 on 2023-03-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0027_remove_addressee_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
