# Generated by Django 4.1.5 on 2023-03-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0028_alter_guest_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
