# Generated by Django 4.1.3 on 2023-03-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0030_alter_guest_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
